# Generated by Django 4.1.6 on 2023-02-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('apis', 'Apis'), ('studis', 'Studis')], max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='LDAPAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LDAPActionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.ManyToManyField(to='apis_rilec.ldapaction')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_rilec.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=256)),
                ('data', models.CharField(max_length=512)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_rilec.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='OUData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('OU', models.CharField(max_length=256)),
                ('short_OU', models.CharField(max_length=32)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_rilec.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='LDAPApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apis_rilec.ldapactionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis_rilec.datasource'),
        ),
    ]
