# Generated by Django 4.1.7 on 2023-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_rilec', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='translationrule',
            index=models.Index(fields=['table'], name='apis_rilec__table_i_9222b2_idx'),
        ),
        migrations.AddIndex(
            model_name='translationrule',
            index=models.Index(fields=['pattern'], name='apis_rilec__pattern_848839_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatafield',
            index=models.Index(fields=['userdata'], name='apis_rilec__userdat_faf027_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatafield',
            index=models.Index(fields=['field'], name='apis_rilec__field_ebf170_idx'),
        ),
    ]
