# Generated by Django 5.1 on 2024-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_rilec', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['uid'], name='apis_rilec__uid_2d6ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['source'], name='apis_rilec__source_3b9eb2_idx'),
        ),
    ]
