# Generated by Django 5.2.7 on 2025-10-27 21:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_rilec", "0002_ldapobject_apis_rilec__uid_2d6ff4_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ldapfield",
            name="field_value_unique",
        ),
        migrations.AddConstraint(
            model_name="ldapfield",
            constraint=models.UniqueConstraint(
                fields=("field", django.db.models.functions.text.MD5("value")),
                name="field_value_unique",
            ),
        ),
    ]
