# Generated by Django 4.1.7 on 2023-08-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_rilec', '0002_translationrule_apis_rilec__table_i_9222b2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=256)),
                ('value', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='LDAPObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sources', models.CharField(choices=[('AD', 'Active Directory'), ('rilec', 'Apis rilec')], default='AD', max_length=64)),
                ('dn', models.TextField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=64, null=True)),
                ('upn', models.CharField(blank=True, max_length=256, null=True)),
                ('objectSid', models.BinaryField(blank=True, max_length=28, null=True)),
                ('fields', models.ManyToManyField(to='apis_rilec.ldapfield')),
            ],
        ),
        migrations.AddIndex(
            model_name='ldapfield',
            index=models.Index(fields=['field'], name='apis_rilec__field_5f273f_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapfield',
            index=models.Index(fields=['field', 'value'], name='apis_rilec__field_b8424c_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['timestamp', 'dn'], name='apis_rilec__timesta_98e050_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['timestamp', 'objectSid'], name='apis_rilec__timesta_06055d_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['timestamp', 'uid'], name='apis_rilec__timesta_596fce_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['timestamp', 'upn'], name='apis_rilec__timesta_a0d172_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['timestamp'], name='apis_rilec__timesta_2552c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['dn'], name='apis_rilec__dn_f1ce9e_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['uid'], name='apis_rilec__uid_2d6ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['upn'], name='apis_rilec__upn_3187a9_idx'),
        ),
        migrations.AddIndex(
            model_name='ldapobject',
            index=models.Index(fields=['objectSid'], name='apis_rilec__objectS_8ec196_idx'),
        ),
    ]
