# Generated by Django 4.1.7 on 2023-03-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_rilec', '0002_datasource_subsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapaction',
            name='action',
            field=models.CharField(choices=[('user_upsert', 'Upsert user data'), ('group_upsert', 'Upsert group data'), ('add', 'Add'), ('modify', 'Modify'), ('delete', 'Delete')], max_length=16),
        ),
        migrations.CreateModel(
            name='TranslationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('flags', models.JSONField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_rilec.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('replacement', models.TextField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='apis_rilec.translationtable')),
            ],
        ),
    ]
