# Generated by Django 4.1.7 on 2023-08-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_rilec', '0004_rename_sources_ldapobject_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapapply',
            name='action',
        ),
        migrations.DeleteModel(
            name='LDAPAction',
        ),
        migrations.DeleteModel(
            name='LDAPActionBatch',
        ),
        migrations.DeleteModel(
            name='LDAPApply',
        ),
    ]
