# Generated by Django 4.1.7 on 2023-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_rilec', '0005_remove_ldapapply_action_delete_ldapaction_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ldapfield',
            name='apis_rilec__field_5f273f_idx',
        ),
        migrations.RemoveIndex(
            model_name='ldapobject',
            name='apis_rilec__timesta_2552c5_idx',
        ),
        migrations.AddField(
            model_name='ldapobject',
            name='objectType',
            field=models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['timestamp'], name='apis_rilec__timesta_887506_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeduserdata',
            index=models.Index(fields=['uid'], name='apis_rilec__uid_831a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='userdata',
            index=models.Index(fields=['uid', 'sub_id'], name='apis_rilec__uid_dee176_idx'),
        ),
    ]
