# Generated by Django 4.1.7 on 2023-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_rilec", "0006_remove_ldapfield_apis_rilec__field_5f273f_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ldapfield",
            constraint=models.UniqueConstraint(
                fields=("field", "value"), name="field_value_unique"
            ),
        ),
    ]
